services:
  - type: web
    name: i-mobile
    runtime: static
    buildCommand: bash website/build.sh
    staticPublishPath: ./website
    autoDeploy: true
    envVars:
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
