import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
class App extends StatelessWidget{const App({super.key});
 @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'ExamPilot AI',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),home:Supabase.instance.client.auth.currentSession==null?const Auth():const Home());}
class Auth extends StatefulWidget{const Auth({super.key});@override State<Auth> createState()=>_Auth();}
class _Auth extends State<Auth>{final e=TextEditingController(),p=TextEditingController();bool up=false;
 Future<void> go()async{try{if(up){await Supabase.instance.client.auth.signUp(email:e.text.trim(),password:p.text);msg('Account created. Check email if required.');}else{await Supabase.instance.client.auth.signInWithPassword(email:e.text.trim(),password:p.text);setState((){});}}catch(x){msg(x.toString());}}
 void msg(String x)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x)));
 @override Widget build(BuildContext c)=>Scaffold(body:Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.school,size:70),const Text('ExamPilot AI',style:TextStyle(fontSize:30,fontWeight:FontWeight.bold)),TextField(controller:e,decoration:const InputDecoration(labelText:'Email')),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'Password')),FilledButton(onPressed:go,child:Text(up?'Create account':'Sign in')),TextButton(onPressed:()=>setState(()=>up=!up),child:Text(up?'Sign in':'Create account'))]))));}}
class Home extends StatelessWidget{const Home({super.key});
 Future<List<Map<String,dynamic>>> exams()=>Supabase.instance.client.from('exams').select().eq('is_active',true).order('name');
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('ExamPilot AI'),actions:[IconButton(onPressed:()=>Supabase.instance.client.auth.signOut(),icon:const Icon(Icons.logout))]),body:FutureBuilder(future:exams(),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final x=List<Map<String,dynamic>>.from(s.data!);return ListView(padding:const EdgeInsets.all(16),children:[const Text('Choose an exam',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),...x.map((e)=>Card(child:ListTile(title:Text(e['name']),subtitle:Text(e['description']??''),trailing:const Icon(Icons.chevron_right),onTap:()=>showDialog(context:c,builder:(_)=>AlertDialog(title:Text(e['name']),content:const Text('Add subjects and questions in Supabase to start CBT practice.'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('OK'))]))))]);}));}}
